### ISSUE TITLE
validation fails in v2.2

### ISSUE THREAD

**Issue by behrisch** [dieghernan/cff-validator#8]
The file https://github.com/eclipse/sumo/blob/bc4df2629e385b463bd7a0b58883c23cb3cd73e4/CITATION.cff validated just fine with v2. The new version triggers several errors: https://github.com/DLR-TS/sumo/actions/runs/3599552359/jobs/6063291364 
This is probably related to the fact that we do not checkout to root but to a separate dir but I did not find a way to tell this fact to the validator.
Is it now required to have the cff file in the root and can we only validate inside a git repo?

**Comment by dieghernan** [comment]
Thanks, this should be fixed now on v2.3 https://github.com/dieghernan/cff-validator/releases/tag/v2.3

**Comment by dieghernan** [comment]
See https://github.com/dieghernan/sumo/actions/runs/3613248528 

CFF validation is not causing errors

**Comment by behrisch** [comment]
Thanks!
